FROM quay.io/sub_mod/centos7-s2i-core:latest
LABEL maintainer="Subin Modeel <smodeel@redhat.com>"
USER root

RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
    && yum -y install curl git jq wget tree 

USER 1001

