FROM quay.io/sub_mod/centos7-s2i-core:latest
LABEL maintainer="Subin Modeel <smodeel@redhat.com>"
USER root

RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
    && yum -y remove git* \
    && yum -y install https://packages.endpoint.com/rhel/7/os/x86_64/endpoint-repo-1.7-1.x86_64.rpm \
    && yum -y install git \
    && git --version \
    && yum -y install curl jq vim wget tree openssh-clients

USER 1001

